openforcefield/openff-nagl

.github/actions/include-openeye/action.yaml
.github/workflows/gh-ci.yaml
devtools/conda-envs/test_env.yaml
openff/nagl/resonance/resonance.py
openff/nagl/resonance/types.py
openff/nagl/tests/conftest.py
openff/nagl/tests/resonance/test_resonance.py

Fixes #
- The toolkit doesn't accept radicals now, this fixes a test to create a weird molecule directly with RDKit.
- 
PR Checklist
------------

fix radical mol and change bond order

---

.github/workflows/gh-ci.yaml
openff/nagl/tests/utils/test_openff.py
openff/nagl/utils/toolkits/__init__.py
openff/nagl/utils/toolkits/registry.py

Fixes #
- 
- 
PR Checklist
------------

Restructure CI

---

openff/nagl/cli/prepare/calculate_similarity.py
openff/nagl/tests/utils/test_openff.py
openff/nagl/utils/openff.py
openff/nagl/utils/toolkits/openeye.py
openff/nagl/utils/toolkits/rdkit.py

Fixes #
- 
- 
PR Checklist
------------

Add fingerprinting redirect

---

openff/nagl/nn/_models.py
openff/nagl/tests/nn/test_model.py

Fixes #
- 
- 
PR Checklist
------------

Fix GNN init failure

---

openff/nagl/tests/data/files.py

Related to #28
- Switch from pkg_resources to importlib_resources
- 
PR Checklist
------------

Migrate from pkg_resources to importlib_resources

---

devtools/conda-envs/docs_env.yaml
setup.py

Fixes #
- This temporarily pins pydantic < 2.0 until the doc extension has time to update.
- 
PR Checklist
------------

Pin pydantic < 2.0

---

CHANGELOG.md
openff/nagl/features/_base.py
openff/nagl/features/_featurizers.py
openff/nagl/features/atoms.py
openff/nagl/molecule/_dgl/molecule.py
openff/nagl/tests/testing/utils.py
openff/nagl/tests/utils/test_openff.py

Fixes #13
- Just uses `Molecule` instead of `OFFMolecule`
- uncomments RMSD test
PR Checklist
------------

Remove offmolecule and uncomment test

---

devtools/conda-envs/test_env.yaml
openff/nagl/config/model.py
openff/nagl/domains.py
openff/nagl/nn/_models.py
openff/nagl/tests/data/example_model_config.yaml
openff/nagl/tests/data/example_training_config.yaml
openff/nagl/tests/data/example_training_config_lazy.yaml
openff/nagl/tests/nn/test_model.py
openff/nagl/tests/test_domain.py

Fixes #
- This adds warnings/errors for if a molecule falls outside a training set
- Also adds versioning to the Model in case we change it again in the future
PR Checklist
------------

Add domains, versioning, and tests

---

CHANGELOG.md

Fixes #
- 
- 
PR Checklist
------------

update changelog for v0.3.1

---

CHANGELOG.md

Fixes #
- 
- 
PR Checklist
------------

Update CHANGELOG for v0.3.2

---

docs/installation.md

Fixes #67
- Add instructions to install NAGL from source
- 
PR Checklist
------------

Add install from source instructions

---

CHANGELOG.md
openff/nagl/tests/utils/test_openff.py
openff/nagl/toolkits/openeye.py
openff/nagl/toolkits/rdkit.py

Fixes #69
- Fixed conversion of `to_openeye` and `to_rdkit` to use the original wrapper methods
PR Checklist
------------

Fixes openeye/rdkit conversion

---

CHANGELOG.md

Fixes #
- 
- 
PR Checklist
------------

Update changelog for 0.3.3

---

CHANGELOG.md

Fixes #
- 
- 
PR Checklist
------------

add Irfan to changelog

---

.github/workflows/dev-ci.yaml
.github/workflows/gh-ci.yaml
devtools/conda-envs/nightly.yaml

Fixes #84 
- 
- 
PR Checklist
------------

Add nightly builds

---

.github/workflows/gh-ci.yaml
setup.py

This PR adds back support for 3.9, which we should keep until at least April!
- 
- 
PR Checklist
------------

Add back 3.9 support

---

CHANGELOG.md

Terrible at remembering to do this in the PR itself. 
PR Checklist
------------

Update changelog with current commits

---

.github/workflows/examples-ci.yaml
devtools/conda-envs/examples_env.yaml

This adds examples CI to NAGL. Largely just a copy of the normal GitHub CI, with nbval installed. Right now it only tests the case where both RDKit and OpenEye are installed -- we may want to expand this in the future.
PR Checklist
------------

Add examples CI

---

.github/workflows/examples-ci.yaml
.github/workflows/gh-ci.yaml
setup.py

Reverts openforcefield/openff-nagl#89
NEP 29's 3.10+ standard drops today

Revert "Add back 3.9 support"

---

CHANGELOG.md
openff/nagl/nn/_containers.py
openff/nagl/nn/_models.py
openff/nagl/tests/nn/test_model.py

Adds some helper functions for looking at pre-postprocessed values. Also allows loading models with kwargs
PR Checklist
------------

Add unprocessed methods

---

devtools/conda-envs/docs_env.yaml
devtools/conda-envs/examples_env.yaml
devtools/conda-envs/nightly.yaml
devtools/conda-envs/test_env_dgl_false.yaml
devtools/conda-envs/test_env_dgl_true.yaml

This reverts commit f7fb4415156f9532b9a210d89264bb9904756d65.
Fixes #108
- 
- 
PR Checklist
------------

Revert "Pin snappy<1.2 (#107)"

---

CHANGELOG.md

Fixes #
- 
- 
PR Checklist
------------

Update changelog for 0.3.8

---

devtools/conda-envs/nightly.yaml
devtools/conda-envs/test_cuda_env.yaml
devtools/conda-envs/test_env_dgl_false.yaml
devtools/conda-envs/test_env_dgl_true.yaml

I don't think this is actually used, although maybe tests will prove me wrong!
PR Checklist
------------

Remove rich library

---

.github/workflows/dev-ci.yaml
devtools/conda-envs/nightly.yaml

This PR fixes some of dev CI (indents the `exclude` job, pulls in `importlib_resources`) but not all of it (i.e. #121)
PR Checklist
------------

Fix dev CI

---

.github/workflows/examples-ci.yaml
.github/workflows/gh-ci.yaml
devtools/conda-envs/docs_env.yaml
devtools/conda-envs/examples_env.yaml
devtools/conda-envs/nightly.yaml
devtools/conda-envs/test_cuda_env.yaml
devtools/conda-envs/test_env_dgl_false.yaml
devtools/conda-envs/test_env_dgl_true.yaml

Fixes #
- 
- 
PR Checklist
------------

Fix remaining problems in CI

---

.github/dependabot.yml
.github/workflows/dev-ci.yaml
.github/workflows/examples-ci.yaml
.github/workflows/gh-ci.yaml

Several actions are using old versions. This updates across the board.

Update ci versions

---

openff/nagl/tests/data/files.py
openff/nagl/tests/nn/test_model.py

Add a couple more tests for lookup tables

---

docs/CHANGELOG.md

Update changelog for v0.4.0

---

docs/CHANGELOG.md
openff/nagl/molecule/_dgl/utils.py
openff/nagl/nn/_models.py
openff/nagl/tests/nn/test_model.py
openff/nagl/tests/utils/test_openff.py
openff/nagl/toolkits/openff.py

Fixes #136 
* Molecules are first fragmented into connected fragments before converting into a nagl molecule and going through models.
* Currently only supports atom-wise properties, although NAGL is meant to be generally formulated
PR Checklist
------------

Add multiple molecule support

---

devtools/conda-envs/test_env_dgl_false.yaml
openff/nagl/tests/label/test_labels.py
openff/nagl/tests/utils/test_openff.py

"Fixes"  #152, ultimately by just skipping the failing test with AmberTools for now.
PR Checklist
------------

Diagnose and fix methane charging

---

openff/nagl/nn/_containers.py
openff/nagl/tests/training/test_training.py

Fixes #155 
- 
- 
PR Checklist
------------

Fix optional postprocess layer

---

docs/CHANGELOG.md

Fixes #
- 
- 
PR Checklist
------------

Update changelog for 0.5.0

---

devtools/conda-envs/base.yaml
devtools/conda-envs/docs_env.yaml
devtools/conda-envs/examples_env.yaml
devtools/conda-envs/nightly.yaml
devtools/conda-envs/test_cuda_env.yaml

Fixes #158
- Do not use `defaults` channel in environments
PR Checklist
------------

Do not use `defaults` channel in environments
